### ISSUE TITLE
pod进来的删除按钮不显示 

### ISSUE THREAD

**Issue by feixiangdepig** [WuOtto/OttoKeyboardView#2]
[button.button setImage:[UIImage imageNamed:@"keyboard_delete"] forState:UIControlStateNormal];

**Comment by WuOtto** [comment]
我这边刚刚新建工程创建pod看了，最新版本(0.0.5)是可以显示的，建议你检查下代码

**Comment by sd1435728** [comment]
引入IQKeyboardManager后确实出现了删除按钮不显示
